# This file is distributed under the same license as the Django package.
#
# Translators:
# Jannis Leidel <jannis@leidel.info>, 2011
# arupakan125 <koh@arupaka.net>, 2020
# Masashi SHIBATA <contact@c-bata.link>, 2017
# Nikita K <hiyori.amatsuki@gmail.com>, 2019
# Shinya Okano <tokibito@gmail.com>, 2013-2016,2021
msgid ""
msgstr ""
"Project-Id-Version: django\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-01-16 12:27+0500\n"
"PO-Revision-Date: 2021-10-13 11:35+0000\n"
"Last-Translator: Shinya Okano <tokibito@gmail.com>\n"
"Language-Team: Japanese (http://www.transifex.com/django/django/language/"
"ja/)\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: .\venv\Lib\site-packages\django\contrib\auth\admin.py:46
msgid "Personal info"
msgstr "個人情報"

#: .\venv\Lib\site-packages\django\contrib\auth\admin.py:47
msgid "Permissions"
msgstr "パーミッション"

#: .\venv\Lib\site-packages\django\contrib\auth\admin.py:50
msgid "Important dates"
msgstr "重要な日程"

#: .\venv\Lib\site-packages\django\contrib\auth\admin.py:134
#, python-format
msgid "%(name)s object with primary key %(key)r does not exist."
msgstr "主キーが %(key)r である %(name)s オブジェクトは存在しません。"

#: .\venv\Lib\site-packages\django\contrib\auth\admin.py:144
msgid "Password changed successfully."
msgstr "パスワードを変更しました"

#: .\venv\Lib\site-packages\django\contrib\auth\admin.py:164
#, python-format
msgid "Change password: %s"
msgstr "パスワードの変更: %s"

#: .\venv\Lib\site-packages\django\contrib\auth\apps.py:16
msgid "Authentication and Authorization"
msgstr "認証と認可"

#: .\venv\Lib\site-packages\django\contrib\auth\base_user.py:48
msgid "password"
msgstr "パスワード"

#: .\venv\Lib\site-packages\django\contrib\auth\base_user.py:49
msgid "last login"
msgstr "最終ログイン"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:41
msgid "No password set."
msgstr "パスワードは設定されませんでした。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:46
msgid "Invalid password format or unknown hashing algorithm."
msgstr "無効なパスワードか不明なハッシュアルゴリズムです。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:84
#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:325
#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:398
msgid "The two password fields didn’t match."
msgstr "確認用パスワードが一致しません。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:87
#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:140
#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:170
#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:402
msgid "Password"
msgstr "パスワード"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:93
msgid "Password confirmation"
msgstr "パスワード(確認用)"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:96
#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:411
msgid "Enter the same password as before, for verification."
msgstr "確認のため、再度パスワードを入力してください。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:142
msgid ""
"Raw passwords are not stored, so there is no way to see this user’s "
"password, but you can change the password using <a href=\"{}\">this form</a>."
msgstr ""
"生のパスワードは格納されていないため、このユーザのパスワードを確認する方法は"
"ありません。しかし<a href=\"{}\">このフォーム</a>を使用してパスワードを変更で"
"きます。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:177
#, python-format
msgid ""
"Please enter a correct %(username)s and password. Note that both fields may "
"be case-sensitive."
msgstr ""
"正しい%(username)sとパスワードを入力してください。どちらのフィールドも大文字"
"と小文字は区別されます。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:180
msgid "This account is inactive."
msgstr "アカウントが無効です。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:243
msgid "Email"
msgstr "メールアドレス"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:328
msgid "New password"
msgstr "新しいパスワード"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:334
msgid "New password confirmation"
msgstr "新しいパスワード(確認用)"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:370
msgid "Your old password was entered incorrectly. Please enter it again."
msgstr "元のパスワードが間違っています。もう一度入力してください。"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:373
msgid "Old password"
msgstr "元のパスワード"

#: .\venv\Lib\site-packages\django\contrib\auth\forms.py:408
msgid "Password (again)"
msgstr "パスワード(確認用)"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:302
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:393
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:482
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:573
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:623
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:664
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:712
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:757
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:805
msgid "algorithm"
msgstr "アルゴリズム"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:303
msgid "iterations"
msgstr "イテレーション"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:304
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:399
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:484
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:577
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:624
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:665
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:806
msgid "salt"
msgstr "ソルト"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:305
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:400
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:578
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:625
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:666
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:713
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:758
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:807
msgid "hash"
msgstr "ハッシュ"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:394
msgid "variety"
msgstr "多様性"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:395
msgid "version"
msgstr "バージョン"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:396
msgid "memory cost"
msgstr "メモリーコスト"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:397
msgid "time cost"
msgstr "時間コスト"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:398
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:576
msgid "parallelism"
msgstr "並行性"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:483
#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:574
msgid "work factor"
msgstr "ワークファクター"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:485
msgid "checksum"
msgstr "チェックサム"

#: .\venv\Lib\site-packages\django\contrib\auth\hashers.py:575
msgid "block size"
msgstr "ブロックサイズ"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:58
#: .\venv\Lib\site-packages\django\contrib\auth\models.py:109
msgid "name"
msgstr "名前"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:62
msgid "content type"
msgstr "コンテンツタイプ"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:64
msgid "codename"
msgstr "コード名"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:69
msgid "permission"
msgstr "パーミッション"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:70
#: .\venv\Lib\site-packages\django\contrib\auth\models.py:112
msgid "permissions"
msgstr "パーミッション"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:119
msgid "group"
msgstr "グループ"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:120
#: .\venv\Lib\site-packages\django\contrib\auth\models.py:247
msgid "groups"
msgstr "グループ"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:238
msgid "superuser status"
msgstr "スーパーユーザー権限"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:241
msgid ""
"Designates that this user has all permissions without explicitly assigning "
"them."
msgstr "全ての権限を持っているとみなされます。"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:250
msgid ""
"The groups this user belongs to. A user will get all permissions granted to "
"each of their groups."
msgstr ""
"このユーザーが所属するグループ。ユーザーはそれぞれのグループに付与されたすべ"
"ての権限を持ちます。"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:258
msgid "user permissions"
msgstr "ユーザーパーミッション"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:260
msgid "Specific permissions for this user."
msgstr "このユーザーの持つ権限です。"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:331
msgid "username"
msgstr "ユーザー名"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:334
msgid "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
msgstr ""
"この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にし"
"てください。"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:337
msgid "A user with that username already exists."
msgstr "同じユーザー名が既に登録済みです。"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:340
msgid "first name"
msgstr "名"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:341
msgid "last name"
msgstr "姓"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:342
msgid "email address"
msgstr "メールアドレス"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:344
msgid "staff status"
msgstr "スタッフ権限"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:346
msgid "Designates whether the user can log into this admin site."
msgstr "ユーザーが管理サイトにログイン可能かどうかを示します。"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:349
msgid "active"
msgstr "有効"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:352
msgid ""
"Designates whether this user should be treated as active. Unselect this "
"instead of deleting accounts."
msgstr ""
"ユーザーがアクティブかどうかを示します。アカウントを削除する代わりに選択を解"
"除してください。"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:356
msgid "date joined"
msgstr "登録日"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:365
msgid "user"
msgstr "ユーザー"

#: .\venv\Lib\site-packages\django\contrib\auth\models.py:366
msgid "users"
msgstr "ユーザー"

#: .\venv\Lib\site-packages\django\contrib\auth\password_validation.py:102
#, python-format
msgid ""
"This password is too short. It must contain at least %(min_length)d "
"character."
msgid_plural ""
"This password is too short. It must contain at least %(min_length)d "
"characters."
msgstr[0] "このパスワードは短すぎます。最低 %(min_length)d 文字以上必要です。"

#: .\venv\Lib\site-packages\django\contrib\auth\password_validation.py:112
#, python-format
msgid "Your password must contain at least %(min_length)d character."
msgid_plural "Your password must contain at least %(min_length)d characters."
msgstr[0] "パスワードは最低 %(min_length)d 文字以上必要です。"

#: .\venv\Lib\site-packages\django\contrib\auth\password_validation.py:151
#, python-format
msgid "The password is too similar to the %(verbose_name)s."
msgstr "このパスワードは %(verbose_name)s と似すぎています。"

#: .\venv\Lib\site-packages\django\contrib\auth\password_validation.py:157
msgid "Your password can’t be too similar to your other personal information."
msgstr "あなたの他の個人情報と似ているパスワードにはできません。"

#: .\venv\Lib\site-packages\django\contrib\auth\password_validation.py:188
msgid "This password is too common."
msgstr "このパスワードは一般的すぎます。"

#: .\venv\Lib\site-packages\django\contrib\auth\password_validation.py:193
msgid "Your password can’t be a commonly used password."
msgstr "よく使われるパスワードにはできません。"

#: .\venv\Lib\site-packages\django\contrib\auth\password_validation.py:203
msgid "This password is entirely numeric."
msgstr "このパスワードは数字しか使われていません。"

#: .\venv\Lib\site-packages\django\contrib\auth\password_validation.py:208
msgid "Your password can’t be entirely numeric."
msgstr "数字だけのパスワードにはできません。"

#: .\venv\Lib\site-packages\django\contrib\auth\templates\registration\password_reset_subject.txt:2
#, python-format
msgid "Password reset on %(site_name)s"
msgstr "%(site_name)s のパスワードリセット"

#: .\venv\Lib\site-packages\django\contrib\auth\validators.py:12
msgid ""
"Enter a valid username. This value may contain only English letters, "
"numbers, and @/./+/-/_ characters."
msgstr ""
"有効なユーザー名を入力してください。半角英数、 @/./+/-/_ を使用できます。"

#: .\venv\Lib\site-packages\django\contrib\auth\validators.py:22
msgid ""
"Enter a valid username. This value may contain only letters, numbers, and "
"@/./+/-/_ characters."
msgstr ""
"有効なユーザー名を入力してください。半角英数、 @/./+/-/_ を使用できます。"

#: .\venv\Lib\site-packages\django\contrib\auth\views.py:164
msgid "Logged out"
msgstr "ログアウト"

#: .\venv\Lib\site-packages\django\contrib\auth\views.py:221
msgid "Password reset"
msgstr "パスワードをリセット"

#: .\venv\Lib\site-packages\django\contrib\auth\views.py:248
msgid "Password reset sent"
msgstr "パスワードリセットを送信しました"

#: .\venv\Lib\site-packages\django\contrib\auth\views.py:258
msgid "Enter new password"
msgstr "新しいパスワードを入力してください"

#: .\venv\Lib\site-packages\django\contrib\auth\views.py:321
msgid "Password reset unsuccessful"
msgstr "パスワードのリセットに失敗しました"

#: .\venv\Lib\site-packages\django\contrib\auth\views.py:329
msgid "Password reset complete"
msgstr "パスワードがリセットされました"

#: .\venv\Lib\site-packages\django\contrib\auth\views.py:341
msgid "Password change"
msgstr "パスワードの変更"

#: .\venv\Lib\site-packages\django\contrib\auth\views.py:364
msgid "Password change successful"
msgstr "パスワードを変更しました"
